# Map between location names and coordinates
location_names:

  # Potreritos primer piso
  - {name: "dinning room",  x: 1.0,  y: 0.2,   frame: "map"}
  - {name: "dining room",   x: 1.0,  y: 0.2,   frame: "map"}
  
  - {name: "kitchen",       x: 0.5,  y: 3.5,   frame: "map"}
  
  - {name: "hall",          x: 2.0,  y: 1.5,   frame: "map"}
  - {name: "hole",          x: 2.0,  y: 1.5,   frame: "map"}
  
  - {name: "visiting",      x: 2.0,  y: 4.0,   frame: "map"}
  - {name: "resting room",  x: 2.0,  y: 4.0,   frame: "map"}
  
  # Generic locations
  - {name: "front",  x: 1.0,  y: 0.0,   frame: "base_footprint"}
  - {name: "back",  x: -1.0,  y: 0.0,   frame: "base_footprint"}
  - {name: "left",  x: 0.0,  y: 1.0,   frame: "base_footprint"}
  - {name: "right",  x: 0.0,  y: -1.0,   frame: "base_footprint"}
  
  - {name: "origin",  x: 0.0,  y: 0.0,   frame: "map"}
  

# List of locations to be visited when patrolling
patrolling_itinerary:
  - "dinning room"
  - "hall"
  - "kitchen"
  - "visiting"
  - "hall"
  - "dinning room"


